### ISSUE TITLE
MockRepository and DefaultValue support?

### ISSUE THREAD

**Issue by robrich** [moq/Moq.AutoMocker#33] opened 2018-04-22 06:29 UTC
Hi Tim and Adam.  Are you open to a PR that would use a `MockRepository` to create all the mocks and support `DefaultValue`?  See https://github.com/Moq/moq4/wiki/Quickstart#customizing-mock-behavior for Moq's `MockRepository` -- towards the end of Customizing, right before Miscellaneous.

**Comment by adamhewitt627** [comment] 2018-04-22 14:30
Interesting thought, I hadn't seen that feature of Moq. At a glance, it looks very much like what AutoMocker does, but I'm on vacation and so can't look at more detail. What are the differences? What value do we add on top of it, especially as a wrapper?

**Comment by robrich** [comment] 2018-04-22 15:40
They're similar and different.  I don't see either as a complete replacement for the other.

`MockRepository` has two sweet spots: 

1. It keeps [`MockBehavor`](https://github.com/moq/moq4/blob/e615aca9de26c0ba9fbea98a08f504ec8c41b6d1/Source/MockBehavior.cs) and [`DefaultValue`](https://github.com/moq/moq4/blob/fbbd829acc4053128aef491321170c1291734518/Source/DefaultValue.cs) and [`Switches`](https://github.com/moq/moq4/blob/master/Source/Switches.cs), defaulting these values when [creating new mocks](https://github.com/moq/moq4/blob/f86759225c46b072c4a721b200b31992d4c54b8b/Source/Obsolete/MockFactory.cs#L334).  In this respect, AutoMocker is similar, though AutoMocker only handles `MockBehavior` currently.

2. It has both `Verify()` and `VerifyAll()` that loops through all mocks, try/catch around the call to each mock, and [throws a single exception at the end](https://github.com/moq/moq4/blob/f86759225c46b072c4a721b200b31992d4c54b8b/Source/Obsolete/MockFactory.cs#L375).

`AutoMocker`'s sweet spot is:

- Creating a real object, discovering the most effective constructor, and using previously supplied values or building new mocks for each constructor parameter.  `MockRepository` has no concept of this.

Because the above lists are quite different, I see no value in one replacing the other.  Rather I see value in using them together.

The changes I'll build in this PR:

1. Add default values to AutoMocker's [constructor](https://github.com/tkellogg/Moq.AutoMocker/issues/33) that additionally take in `DefaultValue` and `Switches`, internally create a `MockRepository`, and persist this rather than the `MockBehavior` it does now.

2. Replace both [`new Mock<T>`](https://github.com/tkellogg/Moq.AutoMocker/blob/b57d3f33e322d9864d49b5b7a542305a80d7aff0/Moq.AutoMock/AutoMocker.cs#L108) and [`Activator.CreateInstance()`](https://github.com/tkellogg/Moq.AutoMocker/blob/master/Moq.AutoMock/Instance.cs#L59) calls (second change is likely best outside [`new MockInstance()`](https://github.com/tkellogg/Moq.AutoMocker/blob/b57d3f33e322d9864d49b5b7a542305a80d7aff0/Moq.AutoMock/AutoMocker.cs#L137)) with calls to `this.mockRepository.Create<T>` (reflected because like `new Mock<T>`, there's no `mockRepository.Create(Type type, ...)`).

3. Replace the guts of [`VerifyAll()`](https://github.com/tkellogg/Moq.AutoMocker/blob/b57d3f33e322d9864d49b5b7a542305a80d7aff0/Moq.AutoMock/AutoMocker.cs#L225) and [`Verify()`](https://github.com/tkellogg/Moq.AutoMocker/blob/b57d3f33e322d9864d49b5b7a542305a80d7aff0/Moq.AutoMock/AutoMocker.cs#L237) with a call to `mockRepository.VerifyAll()` and `mockRepository.Verify()`.  (This change will likely require a semver major version bump because it'll throw one exception at the end rather than throwing on the first mock with mismatched `Setup`s.)

**Comment by adamhewitt627** [comment] 2018-04-22 19:05
So essentially, leverage Moq more fully for creating mocks, and exposing additional control through the AutoMocker API? Sounds reasonable to me. With having to obsolete a Setup method, I'm already figuring we'll be bumping the semver major version, but I want to finalize CI and build scripting before posting it, so this is a good time for this change.

**Comment by robrich** [comment] 2018-04-22 21:56
Looking more closely, `MockRepository` and `Mock.Of<T>()` seem to be at odds as mocks created from `Mock.Of<T>()` don't get into the `MockRepository`'s internal list, and therefore aren't verified with `VerifyAll()`.  See https://github.com/moq/moq4/issues/617.

Though we could augment `AutoMapper.Use()` to reflect into MockRepository's internal list, this is at best fragile.  Probably not a great idea.

I'm thinking of evolving the PR to include:

- Don't use MockRepository
- AutoMocker constructor takes optional DefaultValue, Switches, and CallBase parameters
- Replace VerifyAll and Verify with loop through AutoMocker's `typeMap`, try/catch, throw at end, lifted from [MockRepository](https://github.com/moq/moq4/blob/f86759225c46b072c4a721b200b31992d4c54b8b/Source/Obsolete/MockFactory.cs#L375)

**Comment by Keboo** [comment] 2018-04-23 06:08
I like the direction this is headed. My only suggestion would be to overload the AutoMocker constructor rather than using optional parameters. Optional parameters can be problematic in public library APIs as it can result in unexpected behavior if the call is updated in a later version and the referencing code is not recompiled. Probably an unlikely scenario with unit test code, but I still think good to guard against.

**Comment by robrich** [comment] 2018-05-16 18:11
Created https://github.com/tkellogg/Moq.AutoMocker/pull/34 to add the default parameters
Created https://github.com/tkellogg/Moq.AutoMocker/pull/35 that follows the advice of https://github.com/moq/moq4/issues/617, reflecting into `MockRepository` internals.

**Comment by Keboo** [comment] 2022-02-20 06:15
Going to close this for now as it looks like the previous two PRs have resolved this as far as it can be for now.

**Closed by Keboo** 2022-02-20 06:15 UTC
Labels: enhancement
